export const questions = [
	{
		id: 0,
		stage: 1,
		text: "What is the problem you / team identified ?",
		ans: "",
		type: "text",
	},
	{
		id: 1,
		stage: 1,
		text: "Explain why you identified this problem",
		ans: "",
		type: "text",
	},
	{
		id: 2,
		stage: 2,
		text: "Number of citizens you spoke in order to understand your issue better?",
		ans: "",
		type: "text",
	},
	{
		id: 3,
		stage: 3,
		text: "Why did you decide to choose the above solution to solve the problem?",
		ans: "",
		type: "text",
	},
	{
		id: 4,
		stage: 3,
		text: "How long do you think soluton will last?",
		ans: "",
		type: "text",
	},
	{
		id: 5,
		stage: 4,
		text: "Did you approach (either through WhatsAppSMS/Letter/Email/Meeting) your local government for your solution? (Councillor/MLA/Electricity/Water/Other Agencies)",
		ans: "",
		type: "text",
	},
	{
		id: 6,
		stage: 4,
		text: "In case of water conservation, climate change and waste management, please fill up the amount of waste saved, water saved, carbon footprint after you have undertaken the project",
		ans: "",
		type: "text",
	},
	{
		id: 7,
		stage: 5,
		text: "Who was the mentor of this project?",
		ans: "",
		type: "text",
	},
	{
		id: 8,
		stage: 5,
		text: "Share their contact number and email id",
		ans: "",
		type: "text",
	},
	{
		id: 9,
		stage: 5,
		text: "How long did you work on this project?",
		ans: "",
		type: "text",
	},
	{
		id: 10,
		stage: 1,
		text: "you have a picture of identified problem? Share it here!",
		url: "",
		type: "image",
	},
	{
		id: 11,
		stage: 1,
		text: "you have a video of identified problem? Share its link here!",
		url: "",
		type: "video",
	},
	{
		id: 12,
		stage: 2,
		text: "Have you captured a photo of your interaction? Share it here!",
		url: "",
		type: "image",
	},
	{
		id: 13,
		stage: 2,
		text: "show us how your sample questionnaire looks like?",
		url: "",
		type: "image",
	},
	{
		id: 14,
		stage: 2,
		text: "Have you captured a video of your interaction? Share its link here!",
		url: "",
		type: "video",
	},
	{
		id: 15,
		stage: 3,
		text: "Have you captured a photo of your solution? Share it here!",
		url: "",
		type: "image",
	},
	{
		id: 16,
		stage: 4,
		text: "Share the photo of your implemented solution",
		url: "",
		type: "image",
	},
	{
		id: 17,
		stage: 4,
		text: "Share photos of jingle, awareness campaigns etc? (optional)",
		url: "",
		type: "image",
	},
	{
		id: 18,
		stage: 4,
		text: "Share the videos of your implemented solution",
		url: "",
		type: "video",
	},
];
